### ISSUE TITLE
没有找到data_process.py文件

### ISSUE THREAD

**Issue by Yaoisss** [jiahe7ay/MINI_LLM#1]
+++++++++++++++++
···
3. 切换到dataset_utils目录下运行generate_data.py,运行前修改py文件，将处理数据的函数的注释去掉，才能运行起来
4. 运行data_process.py，在./datasets/目录下生成parquet文件
cd dataset_utils
python data_process.py
···
+++++++++++++++++

这个data_process.py没有找到，看了一下源码是不是generate_data.py？

**Comment by jiahe7ay** [comment]
是的 我写错了

**Comment by jiahe7ay** [comment]
已修改README了 谢谢指正
