### ISSUE TITLE
预训wiki练数据处理问题

### ISSUE THREAD

**Issue by daneren** [jiahe7ay/MINI_LLM#22]
https://github.com/jiahe7ay/MINI_LLM/blob/6115a596b60bab2ed4e0c91e8f00dfe068ca7b29/dataset_utils/generate_data.py#L194C5-L194C55

在代码中对于wikipedia-cn-20230720-filtered.json进行chunk处理，请问为什么要进行这一步呀，会带来效果的提升，还是为了其它什么目的。

**Comment by jiahe7ay** [comment]
只是为了把训练效率尽可能地提高 不浪费一丝占满显存的机会

**Comment by daneren** [comment]
但是这个样子,是否会影响训练效果。
